// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/clients" | "/dashboard/clients/[id]" | "/dashboard/clients/[id]/edit" | "/dashboard/clients/new" | "/dashboard/history" | "/dashboard/profile" | "/dashboard/reports" | "/dashboard/reports/[id]" | "/dashboard/settings" | "/dashboard/users" | "/dashboard/users/[id]" | "/login" | "/report-pdf/[id]"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/auth/accounts" | "/api/auth/register" | "/api/clients" | "/api/clients/[id]" | "/api/clients/[id]/campaigns" | "/api/clients/[id]/report-schedule" | "/api/clients/[id]/send-report" | "/api/clients/meta-options" | "/api/cron/report-jobs" | "/api/cron/send-reports" | "/api/history" | "/api/jobs/health" | "/api/logout" | "/api/meta/validate-token" | "/api/profile" | "/api/reports" | "/api/reports/[id]" | "/api/reports/[id]/cancel" | "/api/reports/[id]/send" | "/api/reports/schedules" | "/api/reports/schedules/bulk" | "/api/settings/evolution" | "/api/settings/import-client" | "/api/settings/meta-account" | "/api/settings/meta-token" | "/api/test/login" | "/api/users" | "/api/users/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/login"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/accounts": {}
  "/api/auth/register": {}
  "/api/clients": {}
  "/api/clients/[id]": { "id": string; }
  "/api/clients/[id]/campaigns": { "id": string; }
  "/api/clients/[id]/report-schedule": { "id": string; }
  "/api/clients/[id]/send-report": { "id": string; }
  "/api/clients/meta-options": {}
  "/api/cron/report-jobs": {}
  "/api/cron/send-reports": {}
  "/api/history": {}
  "/api/jobs/health": {}
  "/api/logout": {}
  "/api/meta/validate-token": {}
  "/api/profile": {}
  "/api/reports": {}
  "/api/reports/[id]": { "id": string; }
  "/api/reports/[id]/cancel": { "id": string; }
  "/api/reports/[id]/send": { "id": string; }
  "/api/reports/schedules": {}
  "/api/reports/schedules/bulk": {}
  "/api/settings/evolution": {}
  "/api/settings/import-client": {}
  "/api/settings/meta-account": {}
  "/api/settings/meta-token": {}
  "/api/test/login": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/dashboard": {}
  "/dashboard/clients": {}
  "/dashboard/clients/[id]": { "id": string; }
  "/dashboard/clients/[id]/edit": { "id": string; }
  "/dashboard/clients/new": {}
  "/dashboard/history": {}
  "/dashboard/profile": {}
  "/dashboard/reports": {}
  "/dashboard/reports/[id]": { "id": string; }
  "/dashboard/settings": {}
  "/dashboard/users": {}
  "/dashboard/users/[id]": { "id": string; }
  "/login": {}
  "/report-pdf/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/login": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
